version: '3'

services:       # Services means what containers we have 
  service:       # container name 1
    build:       
      context: ./     # image into the same directory  
    restart: 'no'
    ports:
      - '8080:8081'
  service-2:      # container name 2
    build:
      context: ./
    restart: always
    ports:
      - '8070:8081'
  service-3:       # container name 3
    build:
      context: ./
    restart: unless-stopped
    ports:
      - '8060:8081'
  service-4:        # container name 4
    build:
      context: ./
    restart: on-failure
    ports:
      - '8050:8081'
  redis_server:
    image: 'redis'      # directly using redis image we don't have to mention it